theme: minima
title: Cognition Bytes by Dyutideepta
description: Physics-Informed AI | Vision Systems | Cross-Disciplinary Innovation
markdown: kramdown

collections:
  posts:
    output: true

# Minima default nav links (top bar)
# You can comment this out if you are using a fully custom navbar
nav:
  - title: Home
    url: /
  - title: Projects
    url: /Project/
  - title: Blog
    url: /blog/
  - title: CV
    url: /assets/DyutideeptaBanerjee_CV.pdf
